## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Install Stage
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - prometheus-community=https://prometheus-community.github.io/helm-charts
  - opencost=https://opencost.github.io/opencost-helm-chart
helm-extra-args: "--timeout 600s"
# upgrade: true # TODO: Uncomment this when we have a proper upgrade path implemented
validate-chart-schema: false
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
excluded-charts: []

skip-clean-up: false # Add this line to prevent cleanup after installation so we can verify installation