blank_issues_enabled: false

contact_links:
  - name: Ask a Question
    url: https://github.com/kubeadapt/kubeadapt-helm/discussions/new
    about: Have a question about using KubeAdapt Helm charts? Start a discussion in our community.
  - name: Documentation
    url: https://github.com/kubeadapt/kubeadapt-helm/tree/main/docs
    about: Check our documentation first - your question might already be answered.
  - name: Security Issue
    url: https://github.com/kubeadapt/kubeadapt-helm/security/policy
    about: Please report security vulnerabilities according to our security policy. 