{{- if and .Values.coreapi.enabled .Values.coreapi.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeadapt.name" . }}-coreapi
  labels:
    {{- include "kubeadapt.labels" . | nindent 4 }}
    app.kubernetes.io/component: coreapi
rules:
  # Node access for node information and metrics
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  
  # Pod access for pod information and metrics
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  
  # Deployment access for workload information
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  
  # HPA access for autoscaling information
  - apiGroups: ["autoscaling", "autoscaling.k8s.io"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  
  # PDB access for disruption budget information
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  
  # Namespace access for namespace information
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
    
  # Service access for service information
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
    
  # ConfigMap and Secret access for configuration information
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
    
  # PersistentVolume and PersistentVolumeClaim access for storage information
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
    
  # Events access for troubleshooting
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeadapt.name" . }}-coreapi
  labels:
    {{- include "kubeadapt.labels" . | nindent 4 }}
    app.kubernetes.io/component: coreapi
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeadapt.name" . }}-coreapi
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubeadapt.name" . }}-coreapi
  apiGroup: rbac.authorization.k8s.io
{{- end }} 