{{- if .Values.coreapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeadapt.name" . }}-coreapi
  labels:
    {{- include "kubeadapt.labels" . | nindent 4 }}
    app.kubernetes.io/component: coreapi
spec:
  type: {{ .Values.coreapi.service.type }}
  ports:
    - port: {{ .Values.coreapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubeadapt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coreapi
{{- end }} 