{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadapt.name" . }}-agent
  labels:
    {{- include "kubeadapt.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
type: Opaque
data:
  token: {{ include "kubeadapt.agentToken" . | b64enc | quote }}
{{- end }} 