{{- $pulse := index .Values "kubeadapt-k8s-pulse" | default dict }}
{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeadapt.name" . }}-agent
  labels:
    {{- include "kubeadapt.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.config.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
    {{- if $pulse.enabled }}
    - port: {{ .Values.global.pulseListenPort }}
      targetPort: pulse
      protocol: TCP
      name: pulse
    {{- end }}
  selector:
    {{- include "kubeadapt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end }}
