name: Renovate
on:
  # The "*" (#42, asterisk) character has special semantics in YAML, so this
  # string has to be quoted.
  schedule:
    - cron: '0 0 * * *'  
  # Manual trigger is also possible
  workflow_dispatch: {}  

permissions:
  contents: read

jobs:
  renovate:
    if: github.repository == 'kubeadapt/kubeadapt-helm'  
    runs-on: ubuntu-latest
    steps:
      - name: Generate token 
        uses: actions/create-github-app-token@67e27a7eb7db372a1c61a7f9bdab8699e9ee57f7 # v1.11.3
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@19e3d87179488d6a0cd9da744d37123ea4b338e5 # v41.0.20
        with:
          configurationFile: .github/configs/renovate-config.js
          renovate-version: 39.153.2
          token: '${{ steps.app-token.outputs.token }}'
          mount-docker-socket: true
        env:
          LOG_LEVEL: 'debug'
          RENOVATE_REPOSITORIES: '${{ github.repository }}'

# TODO: Check up-to-date versions