## Reference: https://github.com/actions/stale
name: Mark stale issues and pull requests
on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Number of days of inactivity before an issue becomes stale
        days-before-stale: 14
        # Number of days of inactivity before a stale issue is closed
        days-before-close: 7
        # Issues with these labels will never be considered stale
        exempt-issue-labels: "security,pinned,bug"
        exempt-pr-labels: "security,pinned,dependencies"
        # Comment to post when marking an issue as stale
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity in the last 14 days. It will be closed in 7 days if no 
          further activity occurs. If this issue is still relevant, please add a comment
          to keep it open. Thank you for your contributions to KubeAdapt.
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          recent activity in the last 14 days. It will be closed in 7 days if no
          further activity occurs. If this PR is still relevant, please update it or
          add a comment to keep it open. Thank you for your contributions to KubeAdapt.
        # Labels to use when marking as stale
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        # Close comment
        close-issue-message: >
          This issue has been automatically closed because it has not had any activity
          for 21 days. Feel free to reopen it if you believe it's still relevant.
        close-pr-message: >
          This pull request has been automatically closed because it has not had any
          activity for 21 days. Feel free to reopen it if you believe it's still relevant.
